# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefenderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='ip адресс клиента')),
                ('total_counter', models.PositiveSmallIntegerField(default=0, verbose_name='Счетчик post-запросов')),
                ('counter', models.PositiveSmallIntegerField(verbose_name='Счетчик post-запросов обнуляемый')),
                ('excess', models.BooleanField(default=True, verbose_name='Доступ разрешен или нет')),
                ('banned_dt', models.DateTimeField(blank=True, null=True, verbose_name='Время до которого запрещен доступ')),
                ('fist_parse', models.DateTimeField(auto_now_add=True)),
                ('last_parse', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IP-адрес',
                'verbose_name_plural': 'Ip-адреса',
                'ordering': ['-last_parse'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, verbose_name='Номер телефона')),
                ('preferred', models.CharField(choices=[('n', 'не указан'), ('p', 'по телефону'), ('e', 'по электронной почте')], default='n', max_length=1, verbose_name='Предпочитаемый способ связи')),
                ('date_time_post', models.DateTimeField(auto_now_add=True, verbose_name='Время обращения')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.DefenderModel', verbose_name='ip клиента')),
            ],
            options={
                'verbose_name': 'Запрос на обратную связь',
                'verbose_name_plural': 'Запросы на обратную связь',
                'ordering': ['-date_time_post'],
            },
        ),
    ]
