# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEmployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100, verbose_name='Организация')),
                ('date_start', models.DateField(db_index=True, verbose_name='Дата устройства на работу')),
                ('date_end', models.DateField(verbose_name='Дата ухода с работы')),
                ('post', models.CharField(max_length=100, verbose_name='Должность')),
                ('content', models.CharField(max_length=5000, verbose_name='Содержание')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.AboutUsModel')),
            ],
            options={
                'verbose_name_plural': 'Опыт работы',
                'verbose_name': 'Предыдущее место работы',
                'ordering': ['-date_start'],
            },
        ),
    ]
